In [2]:
import numpy as np
import sys

In [10]:
#one dimension
a = np.array([1,2,3])
#two dimensions
b = np.array([[1,2,3],[1,2,3]], dtype='int8')
b

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [5]:
#Get dimension
a.ndim

1

In [8]:
#Get shape
b.shape

(2, 3)

In [12]:
#Get type
a.dtype
b.dtype

dtype('int8')

In [13]:
#Get size
a.itemsize

4

In [17]:
#Get total size
a.nbytes

12

**Accessing/Changing specific elements, rows, columns, etc**

In [19]:
a = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(a)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]


In [24]:
#Get specific element [r,c]
a[1,-5]

3

In [25]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
#Get a specific column
a[:,2]

array([3, 3])

In [27]:
#Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [28]:
#changing element
a[1,5]=20

In [30]:
#changing elements
a[:,2]= [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 1,  2,  2,  4,  5, 20,  7]])

**3d example**

In [32]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
#Get specific element (work outside in)
b[0,1,1]

4

In [34]:
#replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

**Initializing Different Types of Arrays**

In [38]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [40]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [42]:
#Any other number full_like
np.full(a.shape,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [45]:
#Random decimal numbers
np.random.rand(*a.shape)

array([[0.32907043, 0.49323026, 0.96331139, 0.93107422, 0.52070479,
        0.09669763, 0.02735749],
       [0.54557223, 0.38189963, 0.6090416 , 0.09872476, 0.40125956,
        0.31042525, 0.84498351]])

In [62]:
# Random integer values
np.random.randint(-4,8,size=(3,3))

array([[ 4,  2, -2],
       [-1,  3,  3],
       [ 1, -1,  0]])

In [64]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
#Repeat
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [69]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
output



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Be careful when copying arrays**

In [75]:
a = np.array([1,2,3])
# b = a
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

**Mathematics**

In [89]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [90]:
a + 2

array([3, 4, 5])

In [79]:
a += 2

In [80]:
a / 2

array([1.5, 2. , 2.5])

In [87]:
a ** 2

array([ 9, 16, 25])

In [82]:
b = np.array([1,0,1,0])

In [88]:
#take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427])

**Linear Algebra**

In [96]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [95]:
c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**

In [101]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.min(stats)

1

In [99]:
np.max(stats,axis=1)

array([3, 6])

In [100]:
np.sum(stats,axis=0)

array([5, 7, 9])

**Reorganizing Arrays**

In [103]:
before = np.array([[1,2,3,4],[5,6,7,8]])

after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [104]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([1,2,3,4])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [107]:
#Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Load Data from File**

In [112]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

**Boolean Masking and Advanced indexing**

In [114]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [115]:
#You can index with a lksit in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [116]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [117]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [118]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [122]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])